config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'home#dashboard'

  resources :users do
    collection do
      get "send_invitation"
      put "create_invitation"
    end
  end

  resources :products  do
    collection do
      get "per_amount"
      get "per_price"
    end
  end


  resources :addresses do
    collection do
      get :find_states
      get :find_cities
      get :get_zip_data
    end
  end

  resources :customers do
     collection do

    end

  end

  resources :contacts do
    member do
      get :select_product
      get :find_product
      get :adding_order
    end
    collection do
      get :product_save
    end
  end
  resources :products do
  end
  resources :orders do
    member do
      put :status
    end
  end

  resources :orders do
  end
  resources :profiles
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :fax , :phone_number, presence: true
  validates :phone_number, length: { minimum:10 ,maximum: 15 }, presence: true
  # has_many :users, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :billing_address, -> { where addressable_type: "BillingAddress"},
     class_name: Address, foreign_key: :addressable_id,
     foreign_type: :addressable_type, dependent: :destroy
  has_one :shipping_address, -> { where addressable_type: "ShippingAddress"},
     class_name: Address, foreign_key: :addressable_id,
     foreign_type: :addressable_type, dependent: :destroy
  has_one :additional_address, -> { where addressable_type: "AdditionalAddress"},
     class_name: Address, foreign_key: :addressable_id,
     foreign_type: :addressable_type, dependent: :destroy
  accepts_nested_attributes_for :shipping_address, allow_destroy: true
  accepts_nested_attributes_for :billing_address, allow_destroy: true
  accepts_nested_attributes_for :additional_address, allow_destroy: true
  accepts_nested_attributes_for :contacts,  allow_destroy: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def new
    @customer = Customer.new
    # @customer.contacts.build
    # @customer.build_shipping_address
    # @customer.build_billing_address
    # @customer.build_additional_address


  end

  def create
    @customer = Customer.new(customer_params)
     respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  def update
    @customer = Customer.find(params[:id])
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end

  end

  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def customer_params
      params.require(:customer).permit(:id, :contact_id,:name, :phone_number, :department, :fax, :_destroy,
                                        contacts_attributes: [
                                          :id,
                                          :name,
                                          :email,
                                          :mob_number,
                                          :_destroy],
                                        shipping_address_attributes: [
                                          :id ,
                                          :line_1 ,
                                          :line_2 ,
                                          :country ,
                                          :state ,
                                          :zip,
                                          :city],
                                        billing_address_attributes: [
                                          :id ,
                                          :line_1 ,
                                          :line_2 ,
                                          :country ,
                                          :state ,
                                          :zip,
                                          :city],
                                        additional_address_attributes: [
                                          :id ,
                                          :line_1 ,
                                          :line_2 ,
                                          :country ,
                                          :state ,
                                          :zip,
                                          :city]
                                          )
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="row">

  <div class="col-sm-12 col-md-12 col-lg-8 col-lg-offset-2 white-box">
    <h1 class="text-center"></h1>
    <%= simple_nested_form_for @customer, html: {class: "form-material form-horizontal"} do |f| %>
      <%= render partial:'customers/shared/form' , locals: {f: f} %>
    <%end%>
  </div>
</div>

app/views/customers/index.html.erb
<div class="col-sm-12">
  <div class="white-box">
      <h3 class="box-title m-b-0 text-center">CUSTOMERS</h3>
      <p class="text-muted m-b-30"></p>
      <div class="table-responsive custom_datatable">
        <table id="companies_datatable" class="display nowrap" cellspacing="0" width="100%">
          <thead>
            <tr>
                <th>Name</th>
                <th>Fax</th>
                <th>Edit</th>
                <th> Destroy</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |contact| %>
              <tr>
                  <td><%= link_to contact.name, contact %></td>
                  <td><%= contact.fax %></td>
                  <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
                  <td><%= link_to 'Destroy', contact, method: :delete, data: {confirm: 'Are yoy sure'} %>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
  </div>
</div>
<script>
  datatable('companies_datatable', 1, [2,3], 20, [0,1])
</script>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-offset-2 col-md-8 col-sm-12 white-box">
    <h1 class="text-center"></h1>
    <%= simple_nested_form_for @customer, html: {class: "form-material form-horizontal"}, url: customers_path , method: :post  do |f| %>
      <%= f.error_notification %>
      <%= render partial:'customers/shared/form' , locals: {f: f} %>
    <%end%>
  </div>
</div>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<form class="form-horizontal form-material col-md-6 col-md-offset-3 white-box">
  <h3> CUSTOMER DETAILS </h3>
  <fieldset>
    <div class="form-group">
      <label class="col-md-3" for="fn">Name</label>
      <div class="col-md-9">
        <span> <%= @customer.name %>
        </span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3" for="fn">Shipping Address</label>
      <div class="col-md-9">
        <p>Line1: <%= @customer.shipping_address.line_1 %></p>
        <p> Line2: <%= @customer.shipping_address.line_2 %></p>
        <p> Zip:<%= @customer.shipping_address.zip %></p>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3" for="fn">Billing Address</label>
      <div class="col-md-9">
        <p>Line1: <%= @customer.billing_address.line_1 %></p>
        <p> Line2: <%= @customer.billing_address.line_2 %></p>
        <p> Zip:<%= @customer.billing_address.zip %></p>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3" for="fn">Additional Address</label>
      <div class="col-md-9">
        <p>Line1: <%= @customer.additional_address.line_1 %></p>
        <p> Line2: <%= @customer.additional_address.line_2 %></p>
        <p> Zip:<%= @customer.additional_address.zip %></p>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3" for="fn">phone:</label>
      <div class="col-md-9">
        <span> <%= @customer.phone_number %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3" for="fn">Fax</label>
      <div class="col-md-9">
        <span>
          <%= @customer.fax%>
        </span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3" for="fn">Department</label>
      <div class="col-md-9">
        <span>
          <%= @customer.department%>
        </span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3" for="fn"> Contact Name</label>
      <div class="col-md-9">
        <span>
          <%= @customer.contacts.name%>
        </span>
      </div>
    </div>
    <div class="col-sm-12">
  <div class="white-box">
    <h3 class="box-title m-b-0 text-center">Contacts</h3>
      <div class="table-responsive custom_datatable">
        <table id="products_datatable" class="display nowrap" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Mobile</th>
              <th>Order</th>
            </tr>
          </thead>
          <tbody>
            <% @customer.contacts.each do |item| %>
              <tr>
                <td><%= item.name %> </td>
                <td><%= item.email %> </td>
                <td><%= item.mob_number %> </td>
                <td><%= link_to 'Order', select_product_contact_path(item, customers_id: @customer.id) %></td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
  </div>
</div>
    <%= link_to 'Edit', edit_customer_path(@customer)%>|
    <%= link_to 'Back', customers_path %>
  </fieldset>
</form>



<script>
  datatable('products_datatable', 1, [0], 20, [0,1,2,3])
</script>