config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'home#dashboard'

  resources :users do
    collection do
      get "send_invitation"
      put "create_invitation"
    end
  end

  resources :products  do
    collection do
      get "per_amount"
      get "per_price"
    end
  end


  resources :addresses do
    collection do
      get :find_states
      get :find_cities
      get :get_zip_data
    end
  end

  resources :customers do
     collection do

    end

  end

  resources :contacts do
    member do
      get :select_product
      get :find_product
      get :adding_order
    end
    collection do
      get :product_save
    end
  end
  resources :products do
  end
  resources :orders do
    member do
      put :status
    end
  end

  resources :orders do
  end
  resources :profiles
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoryt was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
     @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy

    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def index
    @categories = Category.all
  end
  def show
  @category = Category.find(params[:id])
  end
  private
  def category_params
    params.require(:category).permit(:id, :name, :item_code, :cover_slip, :note)
  end
end

app/views/categories/edit.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-offset-2 col-md-8 col-sm-12 white-box">
    <h1 class="text-center">Edit Category</h1>
    <%= simple_nested_form_for @category, html: {class: "form-material form-horizontal"} do |f| %>
      <%= render partial:'categories/shared/form' , locals: {f: f} %>
    <%end%>
  </div>
</div>

app/views/categories/index.html.erb
<div class="col-sm-12">
  <div class="white-box">
    <h3 class="box-title m-b-0 text-center">Categories</h3>
      <div class="table-responsive custom_datatable">
        <table id="products_datatable" class="display nowrap" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Name</th>
              <th>Item code</th>
              <th>Cover Slip</th>
              <th>Note</th>
              <th>Edit</th>
              <th> Delete </th>
            </tr>
          </thead>
            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= link_to category.name, category %></td>
                  <td><%= category.item_code %></td>
                  <td><%= category.cover_slip %></td>
                  <td><%= category.note %></td>
                  <td><%= link_to 'Edit', edit_category_path(category) %></td>
                  <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <%end%>
            </tbody>
        </table>
      </div>
  </div>
</div>

<script>
  datatable('products_datatable', 1, [4,5], 20, [0,1,2,3])
</script>

app/views/categories/new.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-offset-2 col-md-8 col-sm-12 white-box">
    <h1 class="text-center">Create Category</h1>
    <%= simple_nested_form_for @category, html: {class: "form-material form-horizontal"}, url: categories_path , method: :post  do |f| %>
      <%= f.error_notification %>
      <%= render partial:'categories/shared/form' , locals: {f: f} %>
    <%end%>
  </div>
</div>

app/views/categories/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->


<form class="form-horizontal form-material col-md-6 col-md-offset-3 white-box">
  <h3> CATEGORY DETAILS </h3>
  <fieldset>
    <div class="form-group">
      <label class="col-md-3" for="fn">Name:</label>
      <div class="col-md-9">
        <span> <%= @category.name %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3" for="fn">Code:</label>
      <div class="col-md-9">
        <span> <%= @category.item_code %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3" for="fn">Cover Slip</label>
      <div class="col-md-9">
        <span>
          <%= @category.cover_slip %>
        </span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3" for="fn">Note</label>
      <div class="col-md-9">
        <span>
         <%= @category.note %>
        </span>
      </div>
    </div>
    <%= link_to 'Edit', edit_category_path(@category) %> |
    <%= link_to 'Back', categories_path %>

  </fieldset>
</form>