config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'home#dashboard'

  resources :users do
    collection do
      get "send_invitation"
      put "create_invitation"
    end
  end

  resources :products  do
    collection do
      get "per_amount"
      get "per_price"
    end
  end


  resources :addresses do
    collection do
      get :find_states
      get :find_cities
      get :get_zip_data
    end
  end

  resources :customers do
     collection do

    end

  end

  resources :contacts do
    member do
      get :select_product
      get :find_product
      get :adding_order
    end
    collection do
      get :product_save
    end
  end
  resources :products do
  end
  resources :orders do
    member do
      put :status
    end
  end

  resources :orders do
  end
  resources :profiles
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_items, dependent: :destroy
	accepts_nested_attributes_for :order_items,  allow_destroy: true
  validates :name, :price, :stock_in_hand, presence: true
  validates :code, presence: true, uniqueness: true
  belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    @product.order_items.build
  end

  def edit
  end


  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def per_amount
    item_in_stock = Product.find_by(id: params[:product]).stock_in_hand.to_f
    no_of_item = params[:id].to_f
    if item_in_stock >= no_of_item
      item_count = params[:id].to_f
    else
      item_count = -1
    end
    render json: {value: item_count }
  end

  def per_price

    unit_price = (Product.find_by(id: params[:id]).price.to_f).round(2)
    render json: {value: unit_price}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:id,:category_id, :name, :code, :customer_id, :price, :stock_in_hand,
                                    order_items_attributes: [
                                      :id,
                                      :unit_price,
                                      :quantity,
                                      :amount,
                                      :_destroy])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_nested_form_for @product, html: {class: 'form-material form-horizontal'} do |f| %>
  <%= f.error_notification %>
  <div class='form-inputs'>
    <div  class="row">

      <div class='col-md-6'>
        <%= f.input :name, placeholder: 'name' %>
      </div>
      <div class='col-md-6'>
        <%= f.input :code, placeholder: 'code' %>
      </div>
    </div>
    <div  class="row">
      <div class='col-md-6'>
        <%= f.input :price, placeholder: 'price' %>
      </div>
      <div class='col-md-6'>
        <%= f.input :stock_in_hand, placeholder: 'stock in hand' %>
      </div>
    </div>
    <div  class='col-md-6'>
      <%= f.input :category_id, collection: Category.all.map{|i| [i.name, i.id]} %>
    </div>
  </div>
  <div class='col-md-12 text-center'>
    <%= f.submit 'Save',class: 'btn btn-info btn-lg'%>
  </div>
<%end %>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-offset-2 col-md-8 col-sm-12 white-box">
    <h1 class="text-center">Editing Product</h1>
    <%= render 'form', product: @product %>
  </div>
</div>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<div class="col-sm-12">
  <div class="white-box">
    <h3 class="box-title m-b-0 text-center">PRODUCTS</h3>
      <div class="table-responsive custom_datatable">
        <table id="products_datatable" class="display nowrap" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Name</th>
              <th>code</th>
              <th>Price</th>
              <th>Stock</th>
              <th>Edit</th>
              <th> Delete </th>
            </tr>
          </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td><%= link_to product.name, product %></td>
                  <td><%= product.code %></td>
                  <td><%= product.price %></td>
                  <td><%= product.stock_in_hand %></td>
                  <td><%= link_to 'Edit', edit_product_path(product) %></td>
                  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <%end%>
            </tbody>
        </table>
      </div>
  </div>
</div>

<script>
  datatable('products_datatable', 1, [4,5], 20, [0,1,2,3])
</script>

app/views/products/new.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-offset-2 col-md-8 col-sm-12 white-box">
    <h1 class="text-center">Create Product</h1>
    <%= render 'form', product: @product %>
    <%#= link_to 'Back', products_path %>
  </div>
</div>

app/views/products/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->


<form class="form-horizontal form-material col-md-6 col-md-offset-3 white-box">
  <h3> PRODUCT DETAILS </h3>
  <fieldset>
    <div class="form-group">
      <label class="col-md-3" for="fn">Name:</label>
      <div class="col-md-9">
        <span> <%= @product.name %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3" for="fn">Code:</label>
      <div class="col-md-9">
        <span> <%= @product.code %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3" for="fn">Price:</label>
      <div class="col-md-9">
        <span>
          <strong><%= assign_dollar %></strong>
          <%= round_off(@product.price) %>
        </span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3" for="fn">Stock in hand:</label>
      <div class="col-md-9">
        <span>
         <%= @product.stock_in_hand %>
        </span>
      </div>
    </div>
    <%= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Back', products_path %>
  </fieldset>
</form>