config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'home#dashboard'

  resources :users do
    collection do
      get "send_invitation"
      put "create_invitation"
    end
  end

  resources :products  do
    collection do
      get "per_amount"
      get "per_price"
    end
  end


  resources :addresses do
    collection do
      get :find_states
      get :find_cities
      get :get_zip_data
    end
  end

  resources :customers do
     collection do

    end

  end

  resources :contacts do
    member do
      get :select_product
      get :find_product
      get :adding_order
    end
    collection do
      get :product_save
    end
  end
  resources :products do
  end
  resources :orders do
    member do
      put :status
    end
  end

  resources :orders do
  end
  resources :profiles
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true, optional: true
  validates :line_1, :country,  presence: true
  validates :zip, presence: true#,  numericality: { only_integer: true }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/contact.rb
class Contact < ApplicationRecord
	has_one :address, as: :addressable, dependent: :destroy
  has_many :orders, dependent: :destroy
	belongs_to :customer
	accepts_nested_attributes_for :address
	validates :name, presence: true
	validates :mob_number, length: { minimum:10, maximum:15}, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
	                  format: { with: VALID_EMAIL_REGEX },
	                  uniqueness: true
end


def customer_name(obj)
  Customer.find(obj.customer_id).name
end

app/models/county.rb
require 'memoist'

class County < ActiveRecord::Base
  extend Memoist
  belongs_to :state
  has_many :zipcodes

  validates :name, uniqueness: { scope: :state_id, case_sensitive: false },
                   presence: true

  scope :without_zipcodes, -> { joins("LEFT JOIN zipcodes ON zipcodes.county_id = counties.id").where("zipcodes.county_id IS NULL") }
  scope :without_state, -> { where("state_id IS NULL") }

  def cities
    zipcodes.map(&:city).sort.uniq
  end
  memoize :cities
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :fax , :phone_number, presence: true
  validates :phone_number, length: { minimum:10 ,maximum: 15 }, presence: true
  # has_many :users, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :billing_address, -> { where addressable_type: "BillingAddress"},
     class_name: Address, foreign_key: :addressable_id,
     foreign_type: :addressable_type, dependent: :destroy
  has_one :shipping_address, -> { where addressable_type: "ShippingAddress"},
     class_name: Address, foreign_key: :addressable_id,
     foreign_type: :addressable_type, dependent: :destroy
  has_one :additional_address, -> { where addressable_type: "AdditionalAddress"},
     class_name: Address, foreign_key: :addressable_id,
     foreign_type: :addressable_type, dependent: :destroy
  accepts_nested_attributes_for :shipping_address, allow_destroy: true
  accepts_nested_attributes_for :billing_address, allow_destroy: true
  accepts_nested_attributes_for :additional_address, allow_destroy: true
  accepts_nested_attributes_for :contacts,  allow_destroy: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: [ 'ordered', 'paid', 'cancelled', 'completed' ]
	belongs_to :customer, optional: true
	belongs_to :contact, optional: true
	has_many :order_items, dependent: :destroy
  has_one :shipping_address, class_name: "Address", as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :shipping_address
	accepts_nested_attributes_for :order_items,  allow_destroy: true
  validates :order_number, :description, :ordered_at, presence: true
  after_save :set_total_amt


	def order_total_amt
		total = 0
			order_items.each do |i|
				total += i.amount.to_f
			end
		return total
  end

  def set_total_amt
    update_column(:total_amount, order_total_amt)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order, optional: true
	belongs_to :product, optional: true
  validates :quantity, :unit_price, :amount, presence: true

  after_save :update_product_quantity

  def update_product_quantity
    product = Product.find(self.product_id)
    quantity_left = product.stock_in_hand - self.quantity
    product.update_attributes(stock_in_hand: quantity_left)
  end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_items, dependent: :destroy
	accepts_nested_attributes_for :order_items,  allow_destroy: true
  validates :name, :price, :stock_in_hand, presence: true
  validates :code, presence: true, uniqueness: true
  belongs_to :category
end

app/models/state.rb
require 'memoist'

class State < ActiveRecord::Base
  extend Memoist
  has_many :zipcodes
  has_many :counties

  validates :abbr, uniqueness: { case_sensitive: false }, presence: true
  validates :name, uniqueness: { case_sensitive: false }, presence: true

  def cities
    zipcodes.map(&:city).sort.uniq
  end
  memoize :cities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable
  has_one :address, as: :addressable, dependent: :destroy
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  belongs_to :county
  belongs_to :state

  validates :code, uniqueness: true, presence: true
  validates :state_id, :county_id, :city, presence: true

  scope :without_county, -> { where("county_id IS NULL") }
  scope :without_state, -> { where("state_id IS NULL") }
  scope :ungeocoded, -> { where("lat IS NULL OR lon IS NULL") }

  class << self
    def find_by_city_state(city, state)
      includes(county: :state)
        .where("city like ? AND states.abbr like ?", "#{city}%", "%#{state}%")
        .first
    end
  end

  def latlon
    [lat, lon]
  end

  def geocoded?
    (!lat.nil? && !lon.nil?)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def companies_list(user)
  	user.customer.all.map{ |a| a.name}
  end

  def formatted_date(date)
    date.strftime('%d/%m/%Y')
  end
  def round_off(value)
    "%.2f" % value
  end

  def assign_dollar
    return "$"
  end



  def state_select(country)
    CS.get(:"#{country}").map{|k,v| [v,k]}
  end

  def city_select(country, state)
    CS.get(:"#{country}", :"#{state}").map{|k| [k,k]}
  end

  def order_number
    "ORDER-" + "#{Order.count + 1}"
  end
  def total_orders_amount
    Order.sum('total_amount').to_f.round(2)
  end
  def today_sales
    Order.where(ordered_at: Date.today).sum('total_amount').to_f.round(2)
  end
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 col-sm-12">
        <div class="logofooter">
          <%=image_tag 'mobile.png' %>
        </div>
    </div>
    <div class="col-md-9 col-sm-12">
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>
    </div>
  </div>
    <div class="row">
       <div class="col-md-12 text-center">
         2017 &copy; cWs | build-v1.3
       </div>

    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top m-b-0">
  <div class="navbar-header">
    <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse">
      <i class="ti-menu"></i>
    </a>
    <div class="top-left-part logo_img">
      <a class="logo" href="/">
        <b>
          <%= image_tag 'mobile.png'%>
        </b>
        <span class="hidden-xs">
          <%=image_tag 'header_logo1.png' %>
        </span>
      </a>
    </div>
    <ul class="nav navbar-top-links navbar-left hidden-xs active">
      <li><a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
      </li>
      <li class="in">
        <form role="search" class="app-search hidden-xs">
          <input type="text" placeholder="Search..." class="form-control"> <a href="" class="active"><i class="fa fa-search"></i></a>
        </form>
      </li>
    </ul>
    <% if current_user.present?%>
      <ul class="nav navbar-top-links navbar-right pull-right">
        <li class="dropdown ">
          <a class="fa fa-user dropdown-toggle profile-pic" data-toggle="dropdown" href="#"><b class="hidden-xs"><%= current_user.email %></b> </a>
          <ul class="dropdown-menu dropdown-user animated flipInY">
            <li>
              <%= link_to current_user  do%>
                <i class="fa fa-user"></i>
                Profile
              <%end%>
            </li>
            <li>
              <%=link_to destroy_user_session_path, :method=> :delete do %>
                <i class="fa fa-power-off"></i>
                Logout
              <%end%>
            </li>
          </ul>
        </li>
      </ul>
    <%end%>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse slimscrollsidebar">
    <ul class="nav" id="side-menu">
        <li class="nav-small-cap m-t-10"></li>
        <li>
          <a href="/" "data-no-turbolink"="true" class="waves-effect">
            <i class="fa fa-dashboard"></i>
            <span class="hide-menu">
              Dashboard
            </span>
          </a>
        </li>
        <li><a href="javascript:void(0)" class="waves-effect"><i class=" fa fa-qrcode"></i> <span class="hide-menu">Orders <span class="fa arrow"></span></span></a>
            <ul class="nav nav-second-level">
                <li>
                    <%= link_to new_order_path, 'data-no-turbolink' => true do %>
                      <i class="fa fa-plus-square-o"></i>
                      Create
                    <% end %>
                </li>
                <li>
                    <%= link_to orders_path, 'data-no-turbolink' => true do %>
                      <i class="fa fa-list"></i>
                       List
                    <% end %>
                </li>
            </ul>
        </li>
        <li>
          <a href="javascript:void(0)" class="waves-effect">
            <i class="fa fa-suitcase"></i>
              <span class="hide-menu">Customers
                <span class="fa arrow"></span>
              </span>
            </a>
            <ul class="nav nav-second-level">
              <li>
                <%= link_to new_customer_path, 'data-no-turbolink' => true do %>
                  <i class=" fa fa-plus-square-o"></i>
                  <span class="hide-menu">
                    Create Customer
                  </span>
                <% end %>
              </li>
              <li>
                  <%= link_to customers_path, 'data-no-turbolink' => true do %>
                    <i class="fa fa-list"></i>
                     List
                  <% end %>
              </li>
            </ul>
        </li>
        <li><a href="javascript:void(0)" class="waves-effect"><i class=" fa fa-users"></i> <span class="hide-menu">Contacts <span class="fa arrow"></span></span></a>
            <ul class="nav nav-second-level">
                <li>
                    <%= link_to new_contact_path, 'data-no-turbolink' => true do %>
                      <i class="fa fa-plus-square-o"></i>
                      Create
                    <% end %>
                </li>
                <li>
                    <%= link_to contacts_path, 'data-no-turbolink' => true do %>
                      <i class="fa fa-list"></i>
                       List
                    <% end %>
                </li>
            </ul>
        </li>
        <li><a href="javascript:void(0)" class="waves-effect"><i class=" fa fa-users"></i> <span class="hide-menu">Categories <span class="fa arrow"></span></span></a>
            <ul class="nav nav-second-level">
                <li>
                    <%= link_to new_category_path, 'data-no-turbolink' => true do %>
                      <i class="fa fa-plus-square-o"></i>
                      Create
                    <% end %>
                </li>
                <li>
                    <%= link_to categories_path, 'data-no-turbolink' => true do %>
                      <i class="fa fa-list"></i>
                       List
                    <% end %>
                </li>
            </ul>
        </li>
        <li><a href="javascript:void(0)" class="waves-effect"><i class="fa fa-product-hunt"></i> <span class="hide-menu">Products <span class="fa arrow"></span></span></a>
            <ul class="nav nav-second-level">
                <li>
                    <%= link_to new_product_path, 'data-no-turbolink' => true do %>
                      <i class="fa fa-plus-square-o"></i>
                      Create
                    <% end %>
                </li>
                <li>
                    <%= link_to products_path, 'data-no-turbolink' => true do %>
                      <i class="fa fa-list"></i>
                       List
                    <% end %>
                </li>
            </ul>
        </li>
        <li>
          <%= link_to send_invitation_users_path, class: "waves-effect", 'data-no-turbolink' => true do %>
            <i class="fa fa-user"></i>
            <span class="hide-menu">
              Invite User
            </span>
          <% end %>
        </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectCws</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-98340752-2"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments)};
    gtag('js', new Date());
    gtag('config', 'UA-98340752-2');
    </script>
  </head>
  <body>
    <%if current_user.present? %>
    <div id="wrapper">
      <%= render partial: 'layouts/header'%>
      <%= render partial: 'layouts/sidebar'%>
      <div id="page-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <%= yield %>
            </div>
          </div>
    <footer class="footer my_footer center ">
   <%= render partial: 'layouts/footer'%>
   <!-- 2017 &copy; cWs | build-v1.0 -->
</footer>
        </div>
      </div>
  </div>
  <%else%>
  <section id="wrapper" class="login-register">
    <div class="gradient_overlay">
      <div class="login-box">
        <div class="white-box mg_top83">
          <%= yield %>
        </div>
      </div>
    </div
  </section>
<footer class="footer_in center ">
   <%= render partial: 'layouts/footer'%>
   <!-- 2017 &copy; cWs | build-v1.0 -->
</footer>
<%end%>
</body>
</html>